checks:
  php: true

filter:
  excluded_paths:
    - tests/*

build:
  environment:
    php: 7.4.16
  nodes:
    tests: true
    analysis:
      tests:
        override:
          -
            command: phpcs-run
            use_website_config: true
          - php-scrutinizer-run