language: php

php:
  - 7.3

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

install:
  - composer update --prefer-source $PREFER_LOWEST
  - curl -o vendor/bin/php-cs-fixer "https://cs.symfony.com/download/php-cs-fixer-v2.phar"

script:
  - php vendor/bin/php-cs-fixer --no-interaction --dry-run --diff -v fix lib/
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyse
